const sampleListings = [
  {
    title: "Serene Mountain Cottage in Manali",
    description: "A peaceful retreat in the Himalayas. Enjoy stunning mountain views, fresh air, and cozy evenings by the fireplace.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&h=600&q=80",
    price: 3500,
    location: "Manali",
    country: "India",
  },
  {
    title: "Luxury Beachfront Villa in Goa",
    description: "Experience the best of Goa in this stunning villa with a private pool, just steps from the beach. Perfect for a sunny getaway.",
    image: "https://images.unsplash.com/photo-1465101162946-4377e57745c3?auto=format&fit=crop&w=800&h=600&q=80",
    price: 15000,
    location: "Goa",
    country: "India",
  },
  {
    title: "Historic Haveli in Jaipur",
    description: "Step back in time in this beautifully restored haveli in the heart of the Pink City. Experience royal Rajasthani hospitality.",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&h=600&q=80",
    price: 8000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Quaint Houseboat on Kerala Backwaters",
    description: "Float along the tranquil backwaters of Alleppey in a traditional Kettuvallam. A unique and unforgettable experience.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&h=600&q=80",
    price: 6500,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Modern Urban Apartment in Mumbai",
    description: "A stylish and comfortable apartment in the bustling city of Mumbai. Close to major attractions and nightlife.",
    image: "https://images.unsplash.com/photo-1519985176271-adb1088fa94c?auto=format&fit=crop&w=800&h=600&q=80",
    price: 9000,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Riverside Camp in Rishikesh",
    description: "An adventurous stay by the Ganges. Perfect for rafting enthusiasts and those seeking spiritual peace.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&h=600&q=80",
    price: 2500,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Elegant Lake Palace in Udaipur",
    description: "Live like royalty in this stunning palace overlooking Lake Pichola. A truly magical experience.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&h=600&q=80",
    price: 25000,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Colonial Charm in Shimla",
    description: "A beautiful cottage with colonial architecture, offering panoramic views of the surrounding hills.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&h=600&q=80",
    price: 7000,
    location: "Shimla",
    country: "India",
  },
  {
    title: "Tea Plantation Bungalow in Munnar",
    description: "Wake up to the aroma of fresh tea leaves in this charming bungalow set amidst lush green tea gardens.",
    image: "https://images.unsplash.com/photo-1416339306562-f3d12fefd36f?auto=format&fit=crop&w=800&h=600&q=80",
    price: 5500,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Artistic Studio in Kolkata",
    description: "A vibrant and artistic studio apartment in the cultural capital of India. Perfect for creative souls.",
    image: "https://images.unsplash.com/photo-1491555103944-7c647fd857e8?auto=format&fit=crop&w=800&h=600&q=80",
    price: 4000,
    location: "Kolkata",
    country: "India",
  },
  {
    title: "Chic Apartment in South Delhi",
    description: "Explore Delhi from this modern and chic apartment located in a posh South Delhi neighborhood.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&h=600&q=80",
    price: 8500,
    location: "New Delhi",
    country: "India",
  },
  {
    title: "Peaceful Homestay in Puducherry",
    description: "Experience French colonial charm in this peaceful homestay located in the beautiful White Town.",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&h=600&q=80",
    price: 3000,
    location: "Puducherry",
    country: "India",
  },
  {
    title: "Desert Camp under the Stars in Jaisalmer",
    description: "A magical night in the Thar Desert. Enjoy camel safaris, traditional folk music, and a starlit sky.",
    image: "https://images.unsplash.com/photo-1465101178521-1e3b8c7b8ca5?auto=format&fit=crop&w=800&h=600&q=80",
    price: 4500,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Coffee Estate Homestay in Coorg",
    description: "A refreshing stay in the heart of a coffee plantation. Learn about coffee making and enjoy nature trails.",
    image: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=800&h=600&q=80",
    price: 5000,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Mountain View Room in Darjeeling",
    description: "Wake up to a spectacular view of the Kanchenjunga. Enjoy the famous Darjeeling tea and serene environment.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&h=600&q=80",
    price: 4800,
    location: "Darjeeling",
    country: "India",
  },
  {
    title: "Luxury Tent in Ranthambore",
    description: "Combine wildlife adventure with luxury. Stay in a high-end tent near the Ranthambore National Park.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&h=600&q=80",
    price: 12000,
    location: "Ranthambore",
    country: "India",
  },
  {
    title: "Sea View Apartment in Chennai",
    description: "A modern apartment offering stunning views of the Bay of Bengal. Close to the city's cultural hubs.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&h=600&q=80",
    price: 7500,
    location: "Chennai",
    country: "India",
  },
  {
    title: "Yoga Retreat in McLeod Ganj",
    description: "A serene and spiritual retreat in the home of the Dalai Lama. Perfect for meditation and yoga.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&h=600&q=80",
    price: 3200,
    location: "McLeod Ganj",
    country: "India",
  },
  {
    title: "Heritage Hotel in Hampi",
    description: "Stay amidst the ancient ruins of the Vijayanagara Empire. A unique historical experience.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&h=600&q=80",
    price: 6000,
    location: "Hampi",
    country: "India",
  },
  {
    title: "Riverside Cottage in Kasol",
    description: "A cozy cottage by the Parvati river, surrounded by lush green forests and towering mountains.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&h=600&q=80",
    price: 2800,
    location: "Kasol",
    country: "India",
  },
];

module.exports = { data: sampleListings };

